version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    docker:
      - image: circleci/python
    steps:
      - checkout
      - python/install-deps
      - run:
          command: ls
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
