version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          command: ./unit_test.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
